function analyzeResume() {

    let resume = document.getElementById("resumeText").value.toLowerCase();

    let skills = [
        "python",
        "java",
        "sql",
        "html",
        "css",
        "javascript",
        "machine learning",
        "data science",
        "leadership",
        "communication",
        "git",
        "github"
    ];

    let foundSkills = [];
    let score = 0;

    skills.forEach(skill => {
        if (resume.includes(skill)) {
            foundSkills.push(skill);
            score += 8;
        }
    });

    if (resume.includes("project")) score += 10;
    if (resume.includes("internship")) score += 10;
    if (resume.includes("certification")) score += 10;

    if (score > 100) score = 100;

    document.getElementById("score").innerText = score;

    let progressBar = document.getElementById("progressBar");
    progressBar.style.width = score + "%";

    if (score < 60) {
        progressBar.style.backgroundColor = "#ef4444";
    } else if (score < 80) {
        progressBar.style.backgroundColor = "#f59e0b";
    } else {
        progressBar.style.backgroundColor = "#22c55e";
    }

    let scoreElement = document.getElementById("score");

    scoreElement.classList.remove(
        "score-red",
        "score-orange",
        "score-green"
    );

    if (score < 60) {
        scoreElement.classList.add("score-red");
    } else if (score < 80) {
        scoreElement.classList.add("score-orange");
    } else {
        scoreElement.classList.add("score-green");
    }

    let level = "";

    if (score >= 80) {
        level = "Excellent";
    } else if (score >= 60) {
        level = "Good";
    } else if (score >= 40) {
        level = "Average";
    } else {
        level = "Beginner";
    }

    document.getElementById("level").innerText = level;

    let skillsList = document.getElementById("skillsList");
    skillsList.innerHTML = "";

    foundSkills.forEach(skill => {
        let li = document.createElement("li");
        li.textContent = skill;
        skillsList.appendChild(li);
    });

    let suggestions = document.getElementById("suggestions");
    suggestions.innerHTML = "";

    if (!resume.includes("project")) {
        suggestions.innerHTML += "<li>Add Projects Section</li>";
    }

    if (!resume.includes("internship")) {
        suggestions.innerHTML += "<li>Add Internship Experience</li>";
    }

    if (!resume.includes("certification")) {
        suggestions.innerHTML += "<li>Add Certifications</li>";
    }

    if (!resume.includes("github")) {
        suggestions.innerHTML += "<li>Add GitHub Profile</li>";
    }

    if (foundSkills.length < 5) {
        suggestions.innerHTML += "<li>Add More Technical Skills</li>";
    }

    if (foundSkills.length === 0) {
        suggestions.innerHTML += "<li>No skills detected. Improve resume content.</li>";
    }
}

// PDF Upload Feature
document.getElementById("pdfUpload").addEventListener("change", async function (event) {

    const file = event.target.files[0];

    if (!file) return;

    const reader = new FileReader();

    reader.onload = async function () {

        const typedArray = new Uint8Array(this.result);

        const pdf = await pdfjsLib.getDocument(typedArray).promise;

        let text = "";

        for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {

            const page = await pdf.getPage(pageNum);

            const content = await page.getTextContent();

            const strings = content.items.map(item => item.str);

            text += strings.join(" ");
        }

        document.getElementById("resumeText").value = text;
    };

    reader.readAsArrayBuffer(file);
});
function downloadReport() {

    let score = document.getElementById("score").innerText;
    let level = document.getElementById("level").innerText;

    let skills = document.getElementById("skillsList").innerText;

    let suggestions = document.getElementById("suggestions").innerText;

    let report = `
AI RESUME ANALYZER REPORT

ATS Score: ${score}/100

Resume Strength: ${level}

Skills Found:
${skills}

Suggestions:
${suggestions}

Generated by AI Resume Analyzer
`;

    const blob = new Blob([report], { type: "text/plain" });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "Resume_Report.txt";

    document.body.appendChild(a);

    a.click();

    document.body.removeChild(a);

    URL.revokeObjectURL(url);
}
