function downloadReport() {

    let score = document.getElementById("score").innerText;
    let level = document.getElementById("level").innerText;

    let skills = document.getElementById("skillsList").innerText;

    let suggestions = document.getElementById("suggestions").innerText;

    let report = `
AI RESUME ANALYZER REPORT

ATS Score: ${score}/100

Resume Strength: ${level}

Skills Found:
${skills}

Suggestions:
${suggestions}

Generated by AI Resume Analyzer
`;

    const blob = new Blob([report], { type: "text/plain" });

    const url = window.URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "Resume_Report.txt";

    document.body.appendChild(a);

    a.click();

    document.body.removeChild(a);

    window.URL.revokeObjectURL(url);
}
